### ISSUE TITLE
Generator::new_prime returns num_bigint::biguint::BigUint and not num_bigint::BigUint

### ISSUE THREAD

**Issue by tomerdbz** [0xSilene/num-primes#2]
Hey!
so the prime generator returns BigUint from a private module.
This  breaks incompatibility with existing code that uses BigUint.

example of an error:
for
`
let d = e.invmod(&et);
`
we get:
`
expected struct num_bigint::BigUint, found struct num_bigint::biguint::BigUint
`

**Comment by AtropineTears** [comment]
Can you leave sample code that produces the problem?

**Comment by tomerdbz** [comment]
Sure!

https://gist.github.com/rust-play/0345f3bdef665dddc6a2b011985329d1
